theme: jekyll-theme-minimal
title: Hazel's homepage
description: 
College ROI Data
https://github.com/thomasthinks/college-roi-data

This College ROI data analyzes the the colleges and majors that return the best rate of investment(ROI). The data is categorized by major, colleges by state, the downsides of being from out-of-side, what occupation is most exposed by AI, and institutions. With this data, individuals will be better equipped to make informed decisions about the logisitics that surround college, whether it is debating between majors, school, or the decision to attend at all. An individual will be able to decide whether their college route is worth it to their values.

